"""Bid Autopsy: a post-hoc, structured account of why a bid would fail.

satyapramana.md section 11: "the ranked set of blocking requirements, the
specific evidentiary gap behind each, whether the gap is fatal or curable, and
the counterfactual -- 'had these three items been present, this bid would have
moved from FAIL to PASS.'" Deterministic. Derived from the event log, not
regenerated by a model.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Mapping

from satyapramana.verdicts import Judgement, Obligation, Reason, Verdict, compose_judgement, negate

#: Whether a leaf's reason represents positive evidence against the bidder
#: (FATAL -- the same fact, re-checked, will not change) or the absence of
#: evidence / a procedural gap (CURABLE -- new evidence could flip this leaf).
#: A first-pass policy classification, not derived from anything else; revisit
#: it alongside the reason catalogue in docs/VERDICT_ALGEBRA.md if it drifts.
FATAL_REASONS = frozenset({
    Reason.AUTHORITY_CONTRADICTED, Reason.IDENTIFIER_MISMATCH,
    Reason.THRESHOLD_NOT_MET, Reason.DOCUMENT_EXPIRED,
    Reason.REGISTRATION_INACTIVE,
})
CURABLE_REASONS = frozenset({
    Reason.MANDATORY_DOCUMENT_ABSENT, Reason.SUBREQUIREMENT_UNREACHABLE,
    Reason.SELF_DECLARED_CEILING, Reason.CORROBORATION_INCOMPLETE,
    Reason.STALE_VERIFICATION, Reason.AUTHORITY_UNAVAILABLE,
    Reason.AUTHORITY_RATE_LIMITED, Reason.AUTHORITY_NOT_FOUND,
    Reason.AUTHORITY_AMBIGUOUS, Reason.AUTHORITY_MALFORMED,
    Reason.AUTHORITY_UNAUTHORIZED, Reason.AS_OF_UNSUPPORTED,
    Reason.NO_ADAPTER_FOR_FIELD, Reason.EXTRACTION_FAILED,
    Reason.ENTITY_UNRESOLVED, Reason.SUBREQUIREMENTS_UNVERIFIED,
})


def classify(reason: Reason) -> str:
    if reason in FATAL_REASONS:
        return "FATAL"
    if reason in CURABLE_REASONS:
        return "CURABLE"
    return "UNCLASSIFIED"


#: The reason a fresh PASS carries when a leaf is hypothetically satisfied for
#: the counterfactual -- mirrors decide.py's own choice for a satisfied leaf.
_HYPOTHETICAL_PASS = Judgement(Verdict.PASS, Reason.AUTHORITY_CONFIRMED)

_NOT_REASON = {
    Verdict.PASS: Reason.AUTHORITY_CONFIRMED,
    Verdict.FAIL: Reason.AUTHORITY_CONTRADICTED,
    Verdict.PARTIAL: Reason.SUBSET_SATISFIED,
}


def recompose(pack: Mapping[str, Any], leaf_judgements: Mapping[str, Judgement]) -> dict[str, Judgement]:
    """Fold every requirement's verdict up from its leaves, exactly as
    decide.py's walk() does for interior nodes -- but from *given* leaf
    judgements, never re-evaluating evidence. This is what makes the
    counterfactual pure: hand it the real leaves, or the real leaves with a
    handful hypothetically swapped to PASS, and it recomposes either.
    """
    index = {r["id"]: r for r in pack["requirements"]}
    computed: dict[str, Judgement] = {}

    def walk(rid: str) -> Judgement:
        if rid in computed:
            return computed[rid]
        req = index[rid]
        if req["operator"] == "LEAF":
            judgement = leaf_judgements[rid]
        elif req["operator"] == "NOT":
            inner = walk(req["children"][0])
            verdict = negate(inner.verdict)
            reason = _NOT_REASON[verdict] if verdict is not Verdict.UNKNOWN else inner.reason
            judgement = Judgement(verdict, reason)
        else:
            children = [walk(c) for c in req["children"]]
            k = len(children) if req["operator"] == "ALL_OF" else (
                1 if req["operator"] == "ANY_OF" else req["k"])
            judgement = compose_judgement(children, k)
        computed[rid] = judgement
        return judgement

    for rid in index:
        walk(rid)
    return computed


def _roots(pack: Mapping[str, Any]) -> list[str]:
    """Same definition as decide.py's own _roots(): a requirement nobody lists
    as a child is a top-level obligation of the bid."""
    children = {c for r in pack["requirements"] for c in r.get("children", [])}
    return [r["id"] for r in pack["requirements"] if r["id"] not in children]


def _leaves_under(rid: str, index: Mapping[str, Mapping[str, Any]]) -> set[str]:
    req = index[rid]
    if req["operator"] == "LEAF":
        return {rid}
    return {leaf for child in req.get("children", ()) for leaf in _leaves_under(child, index)}


@dataclass(frozen=True)
class BlockingLeaf:
    requirement_id: str
    text: str
    verdict: str
    reason_code: str
    classification: str
    overridden_by: str | None


def autopsy(pack: Mapping[str, Any], verdict_rows: list[Mapping[str, Any]]) -> dict[str, Any]:
    """`verdict_rows` is exactly what proj_verdicts holds for one bidder:
    requirement_id, verdict_system, reason_system, verdict_effective,
    reason_effective, overridden_by, override_justification. Reads the
    *effective* verdict -- what actually determines qualification right now,
    officer overrides included -- but classification and the counterfactual
    use the reason attached to that effective verdict, so an override with no
    justification worth citing still explains itself.
    """
    if not verdict_rows:
        # No requirement has ever been evaluated for this bidder -- vacuously
        # "nothing is blocking" would read as would_qualify: true, which is
        # exactly the confusion the charter's null-vs-zero rule exists to
        # prevent for the metrics. Same principle here: say so, don't imply it.
        return {"would_qualify": None, "blocking_requirements": [], "counterfactual": None,
                "note": "not yet evaluated -- no rule pack has been run against this bidder"}

    index = {r["id"]: r for r in pack["requirements"]}
    by_id = {v["requirement_id"]: v for v in verdict_rows}
    roots = _roots(pack)

    # Qualification hinges on the top-level (root) obligations, not every node
    # in the tree independently -- a root already folds its children, and an
    # officer override lands on the node they actually overrode. Checking
    # every leaf too would make an override at a composite level powerless:
    # the un-overridden leaves underneath it would still read as "blocking"
    # even though the officer's decision is the one that counts.
    blocking_root_ids = [
        rid for rid in roots
        if index[rid]["obligation"] == Obligation.MANDATORY.value
        and by_id.get(rid, {}).get("verdict_effective") != Verdict.PASS.value
    ]
    would_qualify = len(blocking_root_ids) == 0

    blocking_leaf_ids: set[str] = set()
    for rid in blocking_root_ids:
        for lid in _leaves_under(rid, index):
            v = by_id.get(lid)
            if v and v["verdict_effective"] != Verdict.PASS.value:
                blocking_leaf_ids.add(lid)

    blocking = [
        BlockingLeaf(
            requirement_id=lid,
            text=index[lid].get("text", ""),
            verdict=by_id[lid]["verdict_effective"],
            reason_code=by_id[lid]["reason_effective"],
            classification=classify(Reason(by_id[lid]["reason_effective"])),
            overridden_by=by_id[lid].get("overridden_by"),
        )
        for lid in blocking_leaf_ids
    ]
    # FATAL first -- a confirmed problem outranks an administrative gap when an
    # officer is deciding where to spend review time. Stable by requirement_id
    # within a class, so the ranking never depends on set iteration order.
    rank = {"FATAL": 0, "CURABLE": 1, "UNCLASSIFIED": 2}
    blocking.sort(key=lambda b: (rank[b.classification], b.requirement_id))

    curable_ids = [b.requirement_id for b in blocking if b.classification == "CURABLE"]
    counterfactual = None
    if curable_ids and not would_qualify:
        leaf_judgements = {
            rid: Judgement(Verdict(v["verdict_effective"]), Reason(v["reason_effective"]))
            for rid, v in by_id.items()
            if index.get(rid, {}).get("operator") == "LEAF"
        }
        leaf_judgements.update({rid: _HYPOTHETICAL_PASS for rid in curable_ids})
        recomposed = recompose(pack, leaf_judgements)
        still_blocking = [
            rid for rid in roots
            if index[rid]["obligation"] == Obligation.MANDATORY.value
            and recomposed[rid].verdict is not Verdict.PASS
        ]
        counterfactual = {
            "curable_requirement_ids": curable_ids,
            "would_qualify_if_cured": len(still_blocking) == 0,
            "still_blocking_after_cure": sorted(still_blocking),
        }

    return {
        "would_qualify": would_qualify,
        "blocking_requirements": [
            {"requirement_id": b.requirement_id, "text": b.text, "verdict": b.verdict,
             "reason_code": b.reason_code, "classification": b.classification,
             "overridden_by": b.overridden_by}
            for b in blocking
        ],
        "counterfactual": counterfactual,
        "note": None,
    }
